# Generated by Django 4.2.6 on 2023-10-18 14:11

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ContractFile',
            fields=[
                ('auto_increment_id', models.AutoField(primary_key=True, serialize=False)),
                ('fileName', models.CharField(max_length=15)),
                ('publicURI', models.CharField(max_length=255)),
            ],
        ),
    ]
